#define COLOR_RGB(name) name, name##_R = name, name##_G, name##_B

enum color_t
{
	COLOR_RGB(COLOR_ROSEWAWTER),
	COLOR_RGB(COLOR_FLAMINGO),
	COLOR_RGB(COLOR_PINK),
	COLOR_RGB(COLOR_MAUVE),
	COLOR_RGB(COLOR_RED),
	COLOR_RGB(COLOR_MAROON),
	COLOR_RGB(COLOR_PEACH),
	COLOR_RGB(COLOR_GREEN),
	COLOR_RGB(COLOR_SAPPHIRE),
	COLOR_RGB(COLOR_OVERLAY0),
	COLOR_RGB(COLOR_SURFACE2),
	COLOR_RGB(COLOR_SURFACE0),
};

extern const double colors[];

#undef COLOR_RGB
